# Generated by Django 2.2.3 on 2019-07-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='站点名称/地址', max_length=128, unique=True, verbose_name='站点名称/地址')),
                ('project', models.CharField(help_text='gitlab项目名称', max_length=128, unique=True, verbose_name='gitlab项目名称')),
                ('dev_path', models.CharField(help_text='代码保存路径', max_length=128, verbose_name='代码保存路径')),
                ('site_path', models.CharField(help_text='站点目录', max_length=128, verbose_name='站点目录')),
                ('deploy_status', models.BooleanField(default=False, help_text='发布状态', verbose_name='发布状态')),
                ('status', models.IntegerField(default=0, help_text='状态', verbose_name='状态')),
                ('online_version', models.ForeignKey(help_text='线上版本', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_site', to='releases.Release', verbose_name='线上版本')),
                ('pre_version', models.ForeignKey(help_text='预发布版本', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_site', to='releases.Release', verbose_name='预发布版本')),
            ],
            options={
                'db_table': 'site',
                'ordering': ['id'],
            },
        ),
    ]
