# Generated by Django 2.2.3 on 2019-07-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='版本ID', max_length=48, verbose_name='版本ID')),
                ('message', models.CharField(help_text='更改描述', max_length=256, verbose_name='更改描述')),
                ('committed_time', models.DateTimeField(help_text='提交时间', verbose_name='提交时间')),
            ],
            options={
                'db_table': 'release',
                'ordering': ['-committed_time'],
            },
        ),
    ]
