# Generated by Django 2.2.3 on 2019-07-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper_time', models.DateTimeField(auto_now_add=True, help_text='操作时间', verbose_name='操作时间')),
                ('deploy_status', models.IntegerField(default=0, help_text='部署状态', verbose_name='部署状态')),
                ('oper_status', models.IntegerField(default=0, help_text='操作状态', verbose_name='操作状态')),
            ],
            options={
                'db_table': 'oper',
                'ordering': ['-oper_time'],
            },
        ),
    ]
