# Generated by Django 2.2.3 on 2019-07-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('releases', '0001_initial'),
        ('sites', '0001_initial'),
        ('opers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oper',
            name='online_version',
            field=models.ForeignKey(help_text='线上版本', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_oper', to='releases.Release', verbose_name='线上版本'),
        ),
        migrations.AddField(
            model_name='oper',
            name='oper_version',
            field=models.ForeignKey(help_text='操作版本', on_delete=django.db.models.deletion.PROTECT, related_name='oper', to='releases.Release', verbose_name='操作版本'),
        ),
        migrations.AddField(
            model_name='oper',
            name='site',
            field=models.ForeignKey(help_text='所属站点', on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='所属站点'),
        ),
    ]
